### PR TITLE
I added a description

### PR DESCRIPTION
**Pull request by maksymalist**

### CODE REVIEW

**Review by godwin-morwin — APPROVED** [review]

**Comment by godwin-morwin** [comment]
did a great job

**Comment by maksymalist** [comment]
Thanks @Godwindaniel10. But could I ask you for a small favor?

**Comment by godwin-morwin** [comment]
sure

**Comment by maksymalist** [comment]
Could you checkout my project if you don't mind. It will take only a couple of minutes?

**Comment by godwin-morwin** [comment]
Aiit , will do that as soon as i am done doing what i am currntly doing

**Comment by maksymalist** [comment]
Here is the link https://github.com/John8790909/CONNECT

**Comment by godwin-morwin** [comment]
Aiit

**Pull request merged**
