### PR TITLE
committing change in sign-in form

### PR DESCRIPTION
**Pull request by Justobioma**
Hi @Godwindaniel10 
I have created a new sign -in form now for the website. This has both Facebook and Google authentication as well as "Remember Password" feature. 
If you like it, fell free to merge with the rest of the project.
Would you need me to make adjustments, also feel free to ask.

Regards

### CODE REVIEW

**Review by godwin-morwin — APPROVED** [review]
great job

**Comment by godwin-morwin** [comment]
Greate job  once again.
changes

can you make the sign in background color green.
then the Create new account section , you should remove the border then center the text.

**Comment by godwin-morwin** [comment]
You can create a new PR for the changes.

The authentications, are they active yet or you just created the UI? 
can you make it responsive as well?

Thank you @Justobioma

**Comment by Justobioma** [comment]
They are not active yet.On Jun 30, 2021 19:34, Godwin ***@***.***> wrote:
You can create a new PR for the changes.
The authentications, are they active yet or you just created the UI?
Thank you @Justobioma

**Comment by Justobioma** [comment]
Ok no problem.I can look into that for you.CheersOn Jun 30, 2021 19:32, Godwin ***@***.***> wrote:
Greate job  once again.

can you make the sign in background color green.
then the Create new account section , you should remove the border then center the text.

**Comment by godwin-morwin** [comment]
Thanks.
i will create a new issue on the changes and assign it to you

**Pull request merged**
