### PR TITLE
added footers

### PR DESCRIPTION
**Pull request by Beatrix-droid**

### CODE REVIEW

**Review by godwin-morwin — CHANGES_REQUESTED** [review]
@Beatrix-droid  , this commit should have a separate PR. and you did not fully edit this page, still seeing some ( carrot page sections ) , the ( care-for-horses.html ) page should only have information about horses.

**Comment by Beatrix-droid** [comment]
Of course. this was just an initial commit to the horse page, there is still a lot to be done there.
But i’ll submit another Pr for the horse page when i’m Done

**Comment by godwin-morwin** [comment]
@Beatrix-droid Aiit

**Review by godwin-morwin — APPROVED** [review]

**Comment by godwin-morwin** [comment]
@Beatrix-droid do you have an idea on why the footer isn't displaying on my machine, it is just displaying only the background.

or you did not include any LOrem-Ipsum details?

add footer err

**Comment by Beatrix-droid** [comment]
@Godwindaniel10 I did not put any Lorem ipsum data as you said that writing would be added to it later.  So I just put a different colour on the footer to make sure that i could see that it was working and it was visible

**Comment by godwin-morwin** [comment]
Aiit , Great 👍

**Pull request merged**
